<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\TrueCodeApp.Core.Infrastructure\TrueCodeApp.Core.Infrastructure.csproj" />
        <ProjectReference Include="..\TrueCodeApp.Currency.Domain\TrueCodeApp.Currency.Domain.csproj" />
    </ItemGroup>

</Project>
