using FluentMigrator;

namespace TrueCodeApp.Migrator.Migrations;

[Migration(20251103165156)]
public class AddNewTables : ForwardOnlyMigration
{
public override void Up()
{
    var sql = """
              CREATE TABLE IF NOT EXISTS public.currencies
              (
                  "Id"   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                  "Name" TEXT NOT NULL,
                  "Rate" NUMERIC NOT NULL
              );
              
              CREATE TABLE IF NOT EXISTS public.users
              (
                  "Id"       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                  "Login"    VARCHAR(20) NOT NULL,
                  "Password" VARCHAR NOT NULL
              );
              
              CREATE TABLE IF NOT EXISTS public.tokens
              (
                  "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                  "UserId" BIGINT NOT NULL,
                  "Value" TEXT NOT NULL,
                  "ExpiresAt" TIMESTAMPTZ NOT NULL,
                  CONSTRAINT "FK_tokens_users_UserId" FOREIGN KEY ("UserId") REFERENCES public.users ("Id") ON DELETE CASCADE
              );
              
              CREATE TABLE IF NOT EXISTS public.user_currencies
              (
                  "UserId" BIGINT NOT NULL,
                  "CurrencyId" BIGINT NOT NULL,
                  PRIMARY KEY ("UserId", "CurrencyId"),
                  CONSTRAINT "FK_user_currencies_currencies_CurrencyId" FOREIGN KEY ("CurrencyId") REFERENCES public.currencies ("Id") ON DELETE CASCADE,
                  CONSTRAINT "FK_user_currencies_users_UserId" FOREIGN KEY ("UserId") REFERENCES public.users ("Id") ON DELETE CASCADE
              );
              
              CREATE INDEX IF NOT EXISTS "IX_tokens_UserId" ON public.tokens ("UserId");
              CREATE INDEX IF NOT EXISTS "IX_user_currencies_CurrencyId" ON public.user_currencies ("CurrencyId");
              """;
    Execute.Sql(sql);
}
}