<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\TrueCodeApp.Core.Web\TrueCodeApp.Core.Web.csproj" />
      <ProjectReference Include="..\TrueCodeApp.User.Infrastructure\TrueCodeApp.User.Infrastructure.csproj" />
    </ItemGroup>

</Project>
